# -*- coding: utf-8 -*-
"""FINAL PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-BT30SigUw2Ilu9iVfy24pH4S9om_XL

# **TITANIC SURVIVORS**
"""

import pandas as pd
import numpy as np

"""# READING DATA USING PANDAS

We use pandas *read_csv* function to read the csv file in python and pandas *DataFrame* method to convert file into the data frame.
"""

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

df.shape

"""## HANDELLING NULL VALUES"""

df.isnull().sum()

"""Separating out the coloumns which have more than 35% of the values missing in the dataset"""

# df.isnull().sum() returns a pandas series with coloumns name as the label index
# ans the total count of null values in the coloumn as it's value
# And we are storing only these coloumns which have more than 35% of the data missing.

drop_col = df.isnull().sum()[df.isnull().sum()>(35/100 * df.shape[0])]
drop_col

x = df.isnull().sum()
drop_col = x[x>(35/100 * df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()

df.fillna(df.mean(), inplace = True)
df.isnull().sum()

"""Because **Embarked** contains string value, we see the details of that coloumn separately from others as strings doesnot have mean and all."""

df['Embarked'].describe()

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum()              ##NOW ALL THE NULL VALUES HAVE BEEN FILLED

df.corr()

"""Sib Sp=Number of siblings/spouses abroad


Parch=Number of parents/children abroad

So we can make a new coloumn family_size by combining these two coloumns.
"""

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
df.corr()

"""**FamilySize in the ship doesnot have much correlance with survival rate**


Let's check if we whether the person was alone or not can affect the survival rate.

"""

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

"""If the person is he/she has less chance of surviving.



The reason might be the person who is traveling with his family might be belonging to rich class and might be proritized over other.
"""

df[['Alone','Fare']].corr()

"""So we can see if the person was not alone,the chance the ticket price higher is high."""

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]   #1 for female,0 for male
df.groupby(['Sex'])['Survived'].mean()

"""It shows female passengers have more chance of surviving than male ones



It shows women were prioritized over man

"""

df.groupby(['Embarked'])['Survived'].mean()

"""# CONCLUSION

* Female passengers were prioritized over men.

*   People with high class or rich people have higher survival rate than others.Thee hierarchy might have been followed while saving the passengers.

*   Passengers travelling with their family have higher survival rate.

*   Passengers who boarded the ship at Cherbug,survived more in proportion than the others.
"""